---

- name: apt | ooniprobe dependencies install
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - libgeoip-dev
    - libdumbnet-dev
    - libpcap-dev
    - libssl-dev
    - libffi-dev
    - tor
  async: 3600
  poll: 300

