---

- name: apt | ooniprobe dependencies install
  apt:
    name:
      - build-essential
      - python-pip
      - python-dev
      - libgeoip-dev
      - libdumbnet-dev
      - libpcap-dev
      - libssl-dev
      - libffi-dev
      - tor
    state: present
  async: 3600
  poll: 300
  register: pkg_result
  until: pkg_result is success
