---

- name: Include version-specific variables for Debian/Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_os_family == 'Debian'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"
- name: Include version-specific variables for Alpine
  include_vars: "Alpine.yml"
  when: ansible_os_family == "Alpine"

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: python-sni-workaround.yml

- name: Install pyasn1 via pip
  pip: name="{{ item.n }}" version="{{ item.v }}" state=present
  with_items:
    - { n: pyasn1, v: 0.4.2 }
    - { n: pip, v: 9.0.1 }
- name: Trusty | Install recent setuptools via pip
  pip: name="{{ item.n }}" version="{{ item.v }}" state=present
  with_items:
    - { n: setuptools, v: 34.0.0 }
  when: ansible_distribution_release == 'trusty'

- name: Install ooniprobe via pip
  pip: name="{{ item }}" state=present
  with_items:
    - ooniprobe

## centos7 fail: https://github.com/ansible/ansible-modules-core/issues/5109
- name: add daily task to run ooniprobe
  cron: name="run-ooniprobe" special_time=daily
        user="nobody" job="ooniprobe $THE_OONI_COMMAND"
  when: ooniprobe_with_cron is defined and ooniprobe_with_cron

