---

- name: yum | ooniprobe dependencies install
  yum: name="{{item}}" state=present
  with_items:
    - "@Development tools"
    - python-pip
    - python-devel
    - GeoIP-devel
    - libdnet-devel
    - libpcap-devel
    - openssl-devel
    - libffi-devel
    - tor
    - crontabs

- name: start and enable tor service
  service: name=tor state=started enabled=yes
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
