---

- name: RedHat8+ | Enable PowerTools repo
  ini_file:
    dest: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: "{{ item.o }}"
    value: "{{ item.v }}"
    mode: '0644'
  with_items:
    - { o: enabled, v: '1' }
    - { o: baseurl, v: 'http://mirror.centos.org/$contentdir/$releasever/PowerTools/$basearch/os/' }
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8
