---

- import_tasks: redhat8-powertools.yml

- name: yum | ooniprobe dependencies install
  yum:
    name:
      - "@Development tools"
      - python3-pip
      - python3-devel
      - GeoIP-devel
      - libdnet-devel
      - libpcap-devel
      - openssl-devel
      - libffi-devel
      - tor
      - crontabs
    state: present
  register: pkg_result
  until: pkg_result is success

- name: start and enable tor service
  service: name=tor state=started enabled=yes
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
